### ISSUE TITLE
TypeError: _user$project$Main$exprType is not a function

### ISSUE THREAD

**Issue by nateabele** [elm-tools/parser#11]
I'm sure this is a permutation of some other error. There may be others like it, but this one is mine: https://ellie-app.com/XKBHwsdJyWa1/1

If you inline the function causing the error, i.e. by changing:
```
compare = exprType [ "=", "!=", "<", ">", "<=", ">=" ]
math = exprType [ "*", "/", "+", "-" ]
```
to
```
compare = oneOf (List.map toParser [ "=", "!=", "<", ">", "<=", ">=" ])
math = oneOf (List.map toParser [ "*", "/", "+", "-" ])
```

...then you get `TypeError: f is not a function`. Like things I've seen reported other places, the issue seems to be that the function gets invoked before it's defined. _Unlike_ things I've seen reported other places, juggling definition orders in Elm doesn't seem to have an effect.

While writing (well, attempting to write) this parser, I've also busted the call stack without the use of `repeat` or `zeroOrMore`, and I spent about a day and a half playing thunk roulette with `Cannot read property '_0' of undefined`, so if you're looking for runtime errors, let me know. I've got plenty.

**Comment by evancz** [comment]
This appears to be covered by https://github.com/elm-lang/elm-compiler/issues/1377

If it becomes clear that it is something else, please open a new issue that makes it clear why it is different.

**Comment by evancz** [comment]
I made a better issue to track this https://github.com/elm-lang/elm-compiler/issues/1591
