### ISSUE TITLE
Running float parser on "." results in Debug.crash

### ISSUE THREAD

**Issue by ianmackenzie** [elm-tools/parser#12]
```
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> import Parser
> Parser.run Parser.float "."
Error: Ran into a `Debug.crash` in module `Parser`

This was caused by the `case` expression between lines 733 and 745.
One of the branches ended with a crash and the following value got through:

    Err "could not convert string '.' to a Float"

The message provided by the code author is:

    The `Parser.float` parser seems to have a bug.
Please report an SSCCE to <https://github.com/elm-tools/parser/issues>.
>
```
I'm using `elm-tools/parser` 2.0.1. Presumably this is a similar issue to #1?

**Comment by royalicing** [comment]
I’m also getting this issue

**Comment by MikaelMayer** [comment]
Until they accept my pull request https://github.com/elm-tools/parser/pull/34 which fixes  this error, you can replace the package elm-tools/parser in your `elm-package.json` by the following

    "MikaelMayer/parser": "1.0.0 <= v < 2.0.0"

This would replace the `"elm-tools/parser": "2.0.1 <= v < 3.0.0",` that you might have previously.
Make sure your remove your elm-stuff directory before reinstalling all packages.
I tested it for my project, and it worked. Let me know if you encounter other issues.

**Comment by evancz** [comment]
Fixed in my latest development branch. No more `Debug.crash` in the library. Will come out alongside 0.19
