### ISSUE TITLE
Parser.float doesn't work on negative numbers

### ISSUE THREAD

**Issue by xeniagda** [elm-tools/parser#14]
Pretty much as the title says. If you try to do something like

    Parser.run Parser.float "-3.2"

This results in an error whereas it should give the float -3.2.

**Comment by maximoleinyk** [comment]
@loovjo I was inspired by this library and created my own parser-utils library which is very small and quite handy. I think current issue doesn't exists there. 

It doesn't have documentation yet but I think unit tests can help.

Check this out:
https://github.com/maximoleinyk/elm-parser-utils/blob/master/tests/Spec/BasicParsers.elm

**Comment by evancz** [comment]
Not everyone wants to parse negative numbers. Making a primitive _not_ parse negatives is WAY harder than the other way around.

So for now, write a `oneOf` to handle the starting `-` if you want it. That way you can control exactly what you are getting.

In a later iteration of this library, I will likely add more options.
