### ISSUE TITLE
Parser.int should handle negative signs

### ISSUE THREAD

**Issue by fbonetti** [elm-tools/parser#16]
Same issue as https://github.com/elm-tools/parser/issues/14

```
Parser.run Parser.int "-3"
```

This results in an error whereas it should give the int -3.

**Comment by squareduck** [comment]
I think it's good that this parser does not assume that in every language negative integer is going to be expressed with "-" symbol before the number.

It's relatively easy to create a small parser to express usual negative integers:
```
negativeInt : Parser Int
negativeInt =
    succeed identity
        |. symbol "-"
        |= map (\i -> -i) int
```

**Comment by evancz** [comment]
Having worked with a bunch of parsers to make the Elm compiler, I know I do not want numbers to decide anything about how operators are handled. E.g. is `x-2` equal to math like `x - 2` or a function call like `x -2`?

I thought about it a bunch more though, maybe as a setting, and I think it's better to have folks do what @squareduck suggests. Then you get exactly the behavior you want.
