### ISSUE TITLE
Parser.float on ("e" ++ Int) results in Debug.crash

### ISSUE THREAD

**Issue by pablohirafuji** [elm-tools/parser#17]
## Minimal example

run float "e1"

## Error message

Error: Ran into a `Debug.crash` in module `Parser`

This was caused by the `case` expression between lines 733 and 745.
One of the branches ended with a crash and the following value got through:

    Err "could not convert string 'e1' to a Float"

The message provided by the code author is:

    The `Parser.float` parser seems to have a bug.

## Ellie reproduction

https://ellie-app.com/3LVKfT9BLLSa1/0

**Comment by MikaelMayer** [comment]
Until they accept my pull request https://github.com/elm-tools/parser/pull/34 which fixes  this error, you can replace the package elm-tools/parser in your `elm-package.json` by the following

    "MikaelMayer/parser": "1.0.0 <= v < 2.0.0"

This would replace the `"elm-tools/parser": "2.0.1 <= v < 3.0.0",` that you might have previously.
Make sure your remove your elm-stuff directory before reinstalling all packages.
I tested it for my project, and it worked. Let me know if you encounter other issues.

**Comment by evancz** [comment]
Fixed in my development branch by removing the `Debug.crash` scenario and doing a normal parse failure. Will be released alongside 0.19
