### ISSUE TITLE
Allow users to create their own parsers

### ISSUE THREAD

**Issue by pbiggar** [elm-tools/parser#23]
Right now you can compose parsers, but you can't create new ones from scratch. I believe this would require at least `Parser.Internal.Parser`, `Parser.Internal.Good`, and `Parser.Internal.Bad`. Those aren't exposed, and AFAICT I can't access unexposed functions from another module.

Workaround: I vendored the parser so I could access them.

**Comment by evancz** [comment]
Part of making a quality abstraction is creating an API that can snap together in a sensible way. If folks can peer into the internals however they want, it becomes possible to create crazy parsers that exhibit very strange behavior.

When you create feature requests, please start with a concrete use case. "I need to do X." It may be that the solution you are proposing here is the only way to go for that, but I cannot assess that without any information.

**Comment by pbiggar** [comment]
Ah, ok. My concrete use case was to have a Regex parser, as I had several situations where a char-based parser made it difficult to describe a solution. See #24 for discussion.

At a more general level, the use case is to create a new type of parser that is not currently supported, which is currently impossible (atm, only the library authors can create new parser primitives).
