### ISSUE TITLE
A regex-based parser

### ISSUE THREAD

**Issue by pbiggar** [elm-tools/parser#24]
I created a regex-based parser (included below) that I have found to be incredibly useful. It is often significantly shorter/easier to represent some productions in the regex-based parser than using the built-in parsers, and it can also support things that are extremely difficult/complex (perhaps not impossible, but I couldn't work out how to do them).

This is unsurprising, as parsers often use regex as tokenizers, and regex is of course a means of specifying parsers for "regular languages".

Some examples of things that a regex parser primitive would allow:

- I want to support the JS number syntax. I found it on stackoverflow and fairly trivially translated it for Elm's regex library: `"[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?"`. I think this is possible in the parser, but is awkward (`optional` is a missing parser that would make this easier). This compares well to the 100ish lines to handle Ints in the current implementation.

- In general, it is much easier to find a well-known regex for things on StackOverflow, rather than having to (possibly erroneously) handwrite one (with tons of tests!).

- I want to allow "function names" to be built according to this regex: `"[a-zA-Z:!@#%&\\*\\-_\\+\\|/\\?><]+"`. I think I would struggle to do that in less than 20 lines using existing parsers. A parser that would make this simpler would be "match any char in this string".

- `"\"(?:[^\"\\\\]|\\\\.)*\""` is the elm string version of a regex to match a quoted string, allowing an escaped string inside the string. I couldn't figure out how to do this at all, though I expect it is possible. This regex isn't pretty (mostly due to the need to escape things a lot), but it's a lot prettier than I think this would come out building it the manual way.

- Regexes can be case-insensitive: `"true"` (with case-insensitivity) is a useful way of supporting `[tT][rR][uU][eE]`. A case-insensitive parsing primitive would allow this feature.

- Regex would also support a range of things that aren't currently supported but are supported by regexes. Examples include a range of repeats (would solve #20), character-set negation ([^abc]), greedyness, lookahead, etc. These aren't all great features necessarily, but they can help in a pinch.

- Regex also has very mature implementations in browsers, and this would likely avoid the problems in #14, #16 and #12.

Here's my homemade implementation:
```
token : String -> (String -> a) -> String -> Parser a
token name ctor re =  token_ name ctor ("^" ++ re |> Regex.regex)

tokenCI : String -> (String -> a) -> String -> Parser a
tokenCI name ctor re =  token_ name ctor ("^" ++ re |> Regex.regex |> Regex.caseInsensitive)

token_ : String -> (String -> a) -> Regex.Regex -> Parser a
token_ name ctor re =
  PInternal.Parser <| \({ source, offset, indent, context, row, col } as state) ->
    let substring = String.dropLeft offset source in
    case Regex.find (Regex.AtMost 1) re substring of
      [{match}] -> Good (ctor match) { state | offset = offset + String.length match 
                                                                       , col = col + String.length match}
      [] -> Bad (Parser.Parser.Fail <| "Regex " ++ name ++ " not matched: /" ++ toString re ++ "/") state
      _ -> Debug.crash <| "Should never get more than 1 match for regex: " ++ name
```

**Comment by squareduck** [comment]
Been struggling with implementation of string parser with escaped double quotes.
Here's my current take on it if anyone is in the same boat:
```
validString : Parser String
validString =
    map (String.join "") (repeat zeroOrMore validStringChar)


validStringChar : Parser String
validStringChar =
    oneOf
        [ keep (Parser.AtLeast 1) (\c -> c /= '"' && c /= '\\')
        , map (\_ -> "\"") (keyword "\\\"")
        , map (\_ -> "\\") (keyword "\\\\")
        ]
```

**Comment by evancz** [comment]
I don't think it makes sense to include a regex parser in this library. The cases you mention can be done in the existing API as far as I can tell. E.g. your function names example with `[a-zA-Z:!@#%&\\*\\-_\\+\\|/\\?><]+` is like this:

```elm
functionName : Parser String
functionName =
  keep oneOrMore (\c -> Char.isLower c || Char.isUpper c || String.contains (String.fromChar c) ":!@#%&*-_+|/\\?><")
```

Maybe there is something that really cannot be done, but it should be in its own issue. I think having 5 scenarios of mixed quality is not enough justification for all the trouble adding regex would entail. (I.e. in a future where Elm does not compile to JS, having to implement a regex parser to make this library work would be a self-imposed error IMO)

I wrote a bit about regex in the README of https://github.com/elm-lang/regex which will come out alongside the next version of this package.
