### ISSUE TITLE
Compilation error when using lazy parsers

### ISSUE THREAD

**Issue by pbiggar** [elm-tools/parser#25]
I'm getting an error in the compiled code when I use a lazy parser. Here it is as an Ellie: https://ellie-app.com/dtBXJdLSTa1/0

When minimized, my code looks like this:
```
fnCall : Parser String
fnCall = 
  succeed (always "")
    |= repeat oneOrMore fnArg
    
fnArg : Parser String
fnArg =
  lazy (\_ -> fnCall)
```

This causes the following error:
```
elm.js:18405 Uncaught TypeError: Cannot read property '_0' of undefined
    at Function.func (elm.js:18405)
    at A2 (elm.js:92)
    at elm.js:20657
    at elm.js:23710
(anonymous) @ elm.js:18405
A2 @ elm.js:92
(anonymous) @ elm.js:20657
(anonymous) @ elm.js:23710
ui:1108 Elm threw when called with {}
ui:1109 Uncaught ReferenceError: Elm is not defined
    at ui:1109
```

which corresponds to this (I vendor Parser into my app, but I only change the module names)
```
var _user$project$Parser_Parser$repeat = F2(
	function (count, _p56) {
		var _p57 = _p56;
		var _p59 = _p57._0; // <------------------------HERE
		var _p58 = count;
		if (_p58.ctor === 'Exactly') {
			return _user$project$Parser_Parser_Internal$Parser(
				function (state) {
					return A4(
						_user$project$Parser_Parser$repeatExactly,
						_p58._0,
						_p59,
						{ctor: '[]'},
						state);
				});
		} else {
```

**Comment by pbiggar** [comment]
Figured out a workaround: adding an extra lazy. It's because a function is used that is defined later (fnArg, it's the parameter _p56 in the JS output above, and it's undefined). 

See https://ellie-app.com/dtBXJdLSTa1/1
```
fnCall : Parser String
fnCall = 
  succeed (always "")
    |= repeat oneOrMore (lazy (\_ -> fnArg))
    
fnArg : Parser String
fnArg =
  lazy (\_ -> fnCall)
```

**Comment by evancz** [comment]
This issues has been reported on the compiler (where the root issue exists) many times. I am working on a fix for 0.19

**Comment by evancz** [comment]
In the future, please run these questions by folks on the Elm slack before opening issues. That really helps keep the issues organized and oriented towards clear goals.

**Comment by pbiggar** [comment]
Apologies, should have realized this is a compiler issue.
