### ISSUE TITLE
Support languages with overlapping grammar rules

### ISSUE THREAD

**Issue by pbiggar** [elm-tools/parser#27]
I have two productions with overlapping rules:

(consider the string `4 + 5`, being matched with `oneOf [number, binOpExpr]` where `binOpExpr` references `number` as well.)

 I wrote them the naive way, and discovered that one would commit, preventing the other from running because of the `oneOf` they were in. There was no ordering that would allow them succeed.

I think there is definitely a way of writing a parser in this framework to support the language, so the issue is that I didn't know how to do it. I think it would be useful to have one of these two things:

- control over when to commit and when not to commit, as well as guidance for how to think about committing. I ended up hacking `oneOf`, to ignore committed parsers and keep going.

- a guide to an idiomatic way to write parsers using this framework.

Thanks!

**Comment by evancz** [comment]
You can control when to commit by using the `delayedCommit` functions.

So as I understand, this is a request for more documentation. I cannot do that right now, but I am planning to give more docs for this library as I expand its capabilities. Basically, it is still quite young and raw.

In any case, keeping this issue open will not make the docs happen faster or more reliably, so I will close.

**Comment by pbiggar** [comment]
Can I delayedCommit over any production? That was not obvious to me, though perhaps it should have been.

If I write a paragraph or two about committing for the README, do you have time to review it?

**Comment by pbiggar** [comment]
> Can I delayedCommit over any production?

Ah, delayedCommitMap.
