### ISSUE TITLE
allow substitution of custom Problems for library-generated Problems based on context

### ISSUE THREAD

**Issue by dave-doty** [elm-tools/parser#31]
I apologize if this is not really an issue, but I've had no luck figuring out how to do it, or getting ideas on Slack, [Reddit](https://www.reddit.com/r/elm/comments/7hqxfb/how_to_replace_error_message_generated_by/), or the [Google Group](https://groups.google.com/forum/#!topic/elm-discuss/o-jhyXckbu8).

If an error condition is detected directly by my code while parsing, then I can use
```elm
Parser.fail "my custom error message"
```
But what if the problem is found not directly in my code, but in elm-tools/parser code that I call? For example,
```elm
Parser.list spaces Parser.int
```
If the current text doesn't look like a list of integers, then `Parser.list` will generate a `Problem`, with a readable but robotic error message like `BadOneOf ([ExpectingSymbol ",",ExpectingSymbol "]"])`. But suppose I want to output a custom error message instead of simply reporting the error message contained in the `Problem` generated by `Parser.list`. I can't see how to do this.

It's analogous to (in imperative languages with exceptions) catching an exception thrown by a called function and throwing a new, more informative exception based on the calling context.

The closest workaround I can tell (and a very ugly one) is to put lots of information into the context `String`:
```elm
(Parser.inContext "section_3.2.4.3" <| Parser.list spaces Parser.int)
```
and then to use a big `if` or `case` statement after calling `Parser.run` to check the context to see what part of the parser caused the problem, substituting the custom error message there:
```elm
if context.description == "section_1.1.1.1" then
    ...
else if context.description == "section_1.1.1.2" then
    ...
else if context.description == "section_3.2.4.3" then
    "my custom error message"
else ...
```

**Comment by evancz** [comment]
Having custom types for your context (things besides `String`) should be possible in the next version.
