### ISSUE TITLE
Parser.float parses floats with leading zeros incorrectly

### ISSUE THREAD

**Issue by robx** [elm-tools/parser#33]
Parser.float accepts floats with leading zeros even if they are not immediately before the dot, but parses the result to zero. E.g.

```
> Parser.run Parser.float "00.23"
Ok 0 : Result.Result Parser.Error Float
> Parser.run Parser.float "01"
Ok 0 : Result.Result Parser.Error Float
```

**Comment by MikaelMayer** [comment]
Until they accept my pull request https://github.com/elm-tools/parser/pull/34 which fixes  this error, you can replace the package elm-tools/parser in your `elm-package.json` by the following

    "MikaelMayer/parser": "1.0.0 <= v < 2.0.0"

This would replace the `"elm-tools/parser": "2.0.1 <= v < 3.0.0",` that you might have previously.
Make sure your remove your elm-stuff directory before reinstalling all packages.
I tested it for my project, and it worked. Let me know if you encounter other issues.

**Comment by evancz** [comment]
@robx, what data do you have that needs leading zeros? In many languages they are considered invalid input. E.g. Elm and JavaScript. What is your scenario?

Separate from your scenario, if you can think of other examples where "leading zeros" are considered valid, please share that as well. Languages? Formats like JSON or XML?

**Comment by MikaelMayer** [comment]
Where did you see that leading zeroes are invalid in Javascript? The following code runs perfectly in Chrome Console:

    > 0002
    2
    > parseFloat("0003")
    3

Furthermore, looking at the Javascript spec (the latest) for [parseFloat](https://tc39.github.io/ecma262/#sec-parsefloat-string) states that: 

> A StringNumericLiteral that is decimal may have any number of leading 0 digits.

**Comment by MikaelMayer** [comment]
I'm not @robx but a common scenario where it happens that there are leading zeroes is if you parse a zip code and want to store it as a number (which takes less place than a string)

**Comment by evancz** [comment]
With floating point numbers (as OP mentions) I get the following in Chrome:

```
> 000.123
Uncaught SyntaxError: Unexpected number
```

It is true that integers are weirder though:

```
> 00001111
585
> parseInt("00001111")
1111
```

It treats literals that start with `00` as octal. So it's sort of true that "it does allow leading zeros" but in a very odd way.

I find it hard to have back-and-forth discussions in this format. Can you take 5 or 10 minutes to think of _all_ the cases like zip codes (which is a decent one!) and make a new issue outlining what you think of?

**Comment by MikaelMayer** [comment]
Indeed, thanks for these examples. Actually, one leading zero _and_ the number does not contain 8 or 9 makes the browser parse an octal number. If there is no leading zero or the number contains 8 or 9, it parses it as a decimal

I don't have other cases for parsing numbers with leading zeroes. I think it's fine if you disallow it (but return an `Err`, not crash)

**Comment by robx** [comment]
Ugh. What I described was a clear bug: It's fine to fail to parse leading zeros, that seems like the reasonable thing to do. But the package accepts "00.23" as a float, as 0.

**Comment by evancz** [comment]
Sorry, I misunderstood! I was thinking about allowing leading zeros or not from something else and misinterpreted things. I'll open a new issue to try to reset the emotional tone and make it clear to my future self.
