### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when parsing huge file

### ISSUE THREAD

**Issue by Zinggi** [elm-tools/parser#6]
I don't know the specifics that cause this error, but it consistently happens when I try to parse a large file for [my obj file parser](https://github.com/Zinggi/elm-obj-loader).
This could very well be because I wrote my parser somehow wrong.
I managed to reproduce this on [runelm](runelm.io), here:
https://runelm.io/c/23z

If you change the url from the 'small file' to the 'big file' it will crash.

My actual code is very similar to the provided snippet.

I'm using chrome on linux .

**Comment by evancz** [comment]
Can you parse the big file with `elm-combine`? Or is it too big for that library as well?

Also, @stoeffel and I looked into how to make the parser "pause" or generally use less stack, but we did not find anything, and we saw no significant differences in approach between this library and `elm-combine` on this particular detail.

I think the best we'll be able to do for now is optimize existing functions. For example, it may be possible to rewrite to `zeroOrMore` to not use any stack, but I'd need an SCCEE to pin this down more. **Please update this issue if you can get it down to an SSCCE!**

**Comment by Zinggi** [comment]
Yes, I can parse this file (and bigger ones) with `elm-combine`.    
I'll post again if I manage to create a nice SSCCE

**Comment by Zinggi** [comment]
I managed to create a SSCCE.
```elm
module Main exposing (..)

import Html exposing (Html, text)
import Parser exposing (zeroOrMore, keyword, run)


main =
    view (createBigFile 1000)


createBigFile n =
    String.repeat n "1"


crashWithLotsOfText =
    zeroOrMore (keyword "1")


view txt =
    run crashWithLotsOfText txt
        |> Result.mapError (always "")
        |> Result.map (always "")
        |> (toString >> text)

```
* [Ellie link](https://ellie-app.com/rHLqxTsDMLa1/0)

The problem seems to be, as suspected, with `zeroOrMore`. 
It crashes if I change `1000` to `10000`.

**Comment by evancz** [comment]
This SSCCE is great. Thank you!

I'll see what I can do!

**Comment by evancz** [comment]
Should be fixed by that change. I assume it will also make things a bit faster thanks to less allocation and fewer function calls.

It is a major change because I needed to add the `BadRepeat` problem, so I think I should try to do #7 while I'm here. Whatever happens, I'd like to release this fix later today though.

**Comment by evancz** [comment]
Okay, 2.0.0 is out with the fix. It also has a simpler API overall.

**Comment by Zinggi** [comment]
Great!
I'll give it a try for my obj parser when I find some time.
